# Generated by Django 5.2.7 on 2025-10-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='level',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], default='PRIMARIA', max_length=10, verbose_name='Nivel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school_year',
            field=models.PositiveIntegerField(default=2025, verbose_name='Año escolar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='shift',
            field=models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde')], default='MAÑANA', max_length=10, verbose_name='Turno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono / Celular'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=150, verbose_name='Colegio anterior'),
        ),
        migrations.AlterField(
            model_name='student',
            name='doc_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='DNI / Partida'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'section', 'school_year')},
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Apellidos y nombres')),
                ('relationship', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('APODERADO', 'Apoderado'), ('OTRO', 'Otro')], max_length=20, verbose_name='Parentesco')),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='DNI')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono / Celular')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='matricula.student')),
            ],
        ),
    ]
