# Generated by Django 5.2.7 on 2025-10-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_alter_enrollment_unique_together_enrollment_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name': 'Apoderado', 'verbose_name_plural': 'Apoderados'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='level',
            field=models.CharField(choices=[('Inicial', 'Inicial'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=10, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.section', verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='shift',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=10, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.student', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono / Celular'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Apoderado', 'Apoderado'), ('Otro', 'Otro')], max_length=20, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='matricula.student', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='section',
            name='enrolled',
            field=models.PositiveIntegerField(default=0, verbose_name='Matriculados'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono / Celular'),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Colegio anterior'),
        ),
    ]
